import type { Metadata } from "next";
import "./globals.css";
import React, { ReactNode } from "react";
import  Header from "../components/Header";
import Footer from "../components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" data-lt-installed="true">
      <body style={{
        marginTop: "4rem",
        backgroundColor: "black", 
      }}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
